export const READINESS_REFRESH_CADENCE_SECONDS = 60;
export const READINESS_REFRESH_JITTER_BUDGET_SECONDS = 30;
export const READINESS_EDGE_CACHE_FRESH_SECONDS = 5;
export const READINESS_EDGE_CACHE_STALE_WHILE_REVALIDATE_SECONDS = 10;

export const HEALTHY_READINESS_TTL_SECONDS = 120;
export const FAILED_READINESS_TTL_SECONDS = 10;

export const READINESS_CACHE_CONTROL =
  `public, s-maxage=${READINESS_EDGE_CACHE_FRESH_SECONDS}, ` +
  `stale-while-revalidate=${READINESS_EDGE_CACHE_STALE_WHILE_REVALIDATE_SECONDS}`;
