create extension if not exists pg_cron with schema pg_catalog;

create table if not exists public.observability_readiness_state (
  state_key text primary key,
  status text not null
    check (status in ('not_ready', 'ready')),
  summary jsonb not null,
  expires_at timestamptz not null,
  refresh_owner uuid,
  refresh_lease_until timestamptz not null,
  updated_at timestamptz not null default now(),
  constraint observability_readiness_state_singleton
    check (state_key = 'current'),
  constraint observability_readiness_summary_object
    check (jsonb_typeof(summary) = 'object')
);

alter table public.observability_readiness_state enable row level security;
alter table public.observability_readiness_state force row level security;

revoke all on public.observability_readiness_state
  from public, anon, authenticated;
grant select, insert, update on public.observability_readiness_state
  to service_role;

insert into public.observability_readiness_state (
  state_key,
  status,
  summary,
  expires_at,
  refresh_lease_until
)
values (
  'current',
  'not_ready',
  jsonb_build_object(
    'checks',
    jsonb_build_object(
      'optional', jsonb_build_object('healthy', 0, 'total', 0),
      'required', jsonb_build_object('healthy', 0, 'total', 0)
    ),
    'durationMs',
    0,
    'status',
    'not_ready'
  ),
  '-infinity'::timestamptz,
  '-infinity'::timestamptz
)
on conflict (state_key) do nothing;

create or replace function public.claim_observability_readiness_refresh(
  p_owner uuid,
  p_lease_seconds integer default 10
)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_claimed integer;
begin
  if p_owner is null or p_lease_seconds < 1 or p_lease_seconds > 30 then
    raise exception 'invalid readiness refresh lease';
  end if;

  update public.observability_readiness_state
  set
    refresh_owner = p_owner,
    refresh_lease_until =
      pg_catalog.clock_timestamp() +
      pg_catalog.make_interval(secs => p_lease_seconds),
    updated_at = pg_catalog.clock_timestamp()
  where state_key = 'current'
    and refresh_lease_until <= pg_catalog.clock_timestamp();

  get diagnostics v_claimed = row_count;
  return v_claimed > 0;
end;
$$;

create or replace function public.complete_observability_readiness_refresh(
  p_owner uuid,
  p_status text,
  p_summary jsonb,
  p_ttl_seconds integer
)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_updated integer;
begin
  if p_owner is null
    or p_status not in ('not_ready', 'ready')
    or p_ttl_seconds < 1
    or p_ttl_seconds > 300
    or pg_catalog.jsonb_typeof(p_summary) <> 'object'
    or p_summary ->> 'status' is distinct from p_status
  then
    raise exception 'invalid readiness refresh result';
  end if;

  update public.observability_readiness_state
  set
    status = p_status,
    summary = p_summary,
    expires_at =
      pg_catalog.clock_timestamp() +
      pg_catalog.make_interval(secs => p_ttl_seconds),
    refresh_owner = null,
    refresh_lease_until = '-infinity'::timestamptz,
    updated_at = pg_catalog.clock_timestamp()
  where state_key = 'current'
    and refresh_owner = p_owner
    and refresh_lease_until > pg_catalog.clock_timestamp();

  get diagnostics v_updated = row_count;
  return v_updated > 0;
end;
$$;

revoke all on function public.claim_observability_readiness_refresh(
  uuid,
  integer
) from public, anon, authenticated;
revoke all on function public.complete_observability_readiness_refresh(
  uuid,
  text,
  jsonb,
  integer
) from public, anon, authenticated;
grant execute on function public.claim_observability_readiness_refresh(
  uuid,
  integer
) to service_role;
grant execute on function public.complete_observability_readiness_refresh(
  uuid,
  text,
  jsonb,
  integer
) to service_role;

create table if not exists public.observability_alert_rules (
  alert_key text primary key,
  metric_kind text not null
    check (metric_kind in ('latest', 'ratio')),
  threshold numeric not null check (threshold >= 0),
  window_seconds integer not null check (window_seconds between 1 and 86400),
  minimum_samples integer not null check (minimum_samples between 1 and 100000),
  severity text not null check (severity in ('warn', 'error')),
  cooldown_seconds integer not null check (cooldown_seconds between 1 and 86400),
  recovery_consecutive_samples integer not null
    check (recovery_consecutive_samples between 1 and 1000),
  owner text not null,
  destination text not null
);

create table if not exists public.observability_alert_samples (
  id bigint generated by default as identity primary key,
  alert_key text not null
    references public.observability_alert_rules(alert_key)
    on update cascade
    on delete restrict,
  value numeric not null check (value >= 0 and value <= 1000000000),
  occurred_at timestamptz not null default now()
);

create index if not exists observability_alert_samples_window_idx
  on public.observability_alert_samples (alert_key, occurred_at desc);

create table if not exists public.observability_alert_state (
  alert_key text primary key
    references public.observability_alert_rules(alert_key)
    on update cascade
    on delete restrict,
  active boolean not null default false,
  consecutive_healthy_samples integer not null default 0
    check (consecutive_healthy_samples >= 0),
  last_triggered_at timestamptz,
  last_recovered_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.observability_alert_events (
  id uuid primary key default gen_random_uuid(),
  alert_key text not null
    references public.observability_alert_rules(alert_key)
    on update cascade
    on delete restrict,
  outcome text not null check (outcome in ('triggered', 'recovered')),
  severity text not null check (severity in ('info', 'warn', 'error')),
  metric_value numeric not null check (metric_value >= 0),
  sample_count integer not null check (sample_count >= 1),
  threshold numeric not null check (threshold >= 0),
  window_seconds integer not null check (window_seconds >= 1),
  destination text not null,
  occurred_at timestamptz not null default now()
);

create index if not exists observability_alert_events_lookup_idx
  on public.observability_alert_events (alert_key, occurred_at desc);

alter table public.observability_alert_rules enable row level security;
alter table public.observability_alert_rules force row level security;
alter table public.observability_alert_samples enable row level security;
alter table public.observability_alert_samples force row level security;
alter table public.observability_alert_state enable row level security;
alter table public.observability_alert_state force row level security;
alter table public.observability_alert_events enable row level security;
alter table public.observability_alert_events force row level security;

revoke all on public.observability_alert_rules,
  public.observability_alert_samples,
  public.observability_alert_state,
  public.observability_alert_events
from public, anon, authenticated;
grant select on public.observability_alert_rules,
  public.observability_alert_state,
  public.observability_alert_events
to service_role;
grant select, insert, delete on public.observability_alert_samples
  to service_role;
grant insert, update on public.observability_alert_state
  to service_role;
grant insert on public.observability_alert_events
  to service_role;
grant usage, select on sequence public.observability_alert_samples_id_seq
  to service_role;

insert into public.observability_alert_rules (
  alert_key,
  metric_kind,
  threshold,
  window_seconds,
  minimum_samples,
  severity,
  cooldown_seconds,
  recovery_consecutive_samples,
  owner,
  destination
)
values
  (
    'cron_refresh_missing',
    'latest',
    1,
    900,
    1,
    'error',
    900,
    1,
    'alpha_dog_operations',
    'supabase_observability_alert_events'
  ),
  (
    'import_finalization_failure',
    'latest',
    1,
    300,
    1,
    'error',
    300,
    1,
    'alpha_dog_operations',
    'supabase_observability_alert_events'
  ),
  (
    'paid_usage_anomaly',
    'ratio',
    0.2,
    900,
    20,
    'warn',
    900,
    3,
    'alpha_dog_operations',
    'supabase_observability_alert_events'
  ),
  (
    'provider_error_rate',
    'ratio',
    0.1,
    300,
    20,
    'warn',
    300,
    3,
    'alpha_dog_operations',
    'supabase_observability_alert_events'
  ),
  (
    'stale_screener_snapshot',
    'latest',
    30,
    900,
    1,
    'warn',
    900,
    1,
    'alpha_dog_operations',
    'supabase_observability_alert_events'
  ),
  (
    'workflow_failure',
    'latest',
    1,
    300,
    1,
    'error',
    300,
    1,
    'alpha_dog_operations',
    'supabase_observability_alert_events'
  )
on conflict (alert_key) do update
set
  metric_kind = excluded.metric_kind,
  threshold = excluded.threshold,
  window_seconds = excluded.window_seconds,
  minimum_samples = excluded.minimum_samples,
  severity = excluded.severity,
  cooldown_seconds = excluded.cooldown_seconds,
  recovery_consecutive_samples = excluded.recovery_consecutive_samples,
  owner = excluded.owner,
  destination = excluded.destination;

insert into public.observability_alert_state (alert_key)
select alert_key
from public.observability_alert_rules
on conflict (alert_key) do nothing;

create or replace function public.evaluate_observability_alerts(
  p_now timestamptz default now()
)
returns table (
  event_id uuid,
  alert_key text,
  outcome text,
  severity text
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_rule record;
  v_state public.observability_alert_state%rowtype;
  v_sample_count integer;
  v_metric_value numeric;
  v_should_trigger boolean;
  v_event_id uuid;
begin
  if p_now is null then
    raise exception 'evaluation timestamp is required';
  end if;

  if not pg_catalog.pg_try_advisory_xact_lock(
    pg_catalog.hashtextextended('alpha-dog-observability-alert-evaluator', 0)
  ) then
    return;
  end if;

  for v_rule in
    select r.*
    from public.observability_alert_rules as r
    order by r.alert_key
  loop
    if v_rule.metric_kind = 'ratio' then
      select count(*)::integer, avg(s.value)
      into v_sample_count, v_metric_value
      from public.observability_alert_samples as s
      where s.alert_key = v_rule.alert_key
        and s.occurred_at >
          p_now - pg_catalog.make_interval(secs => v_rule.window_seconds)
        and s.occurred_at <= p_now;
    else
      select 1, s.value
      into v_sample_count, v_metric_value
      from public.observability_alert_samples as s
      where s.alert_key = v_rule.alert_key
        and s.occurred_at >
          p_now - pg_catalog.make_interval(secs => v_rule.window_seconds)
        and s.occurred_at <= p_now
      order by s.occurred_at desc, s.id desc
      limit 1;
    end if;

    if coalesce(v_sample_count, 0) < v_rule.minimum_samples
      or v_metric_value is null
    then
      continue;
    end if;

    v_should_trigger := v_metric_value >= v_rule.threshold;

    select s.*
    into v_state
    from public.observability_alert_state as s
    where s.alert_key = v_rule.alert_key
    for update;

    if v_should_trigger then
      update public.observability_alert_state
      set
        consecutive_healthy_samples = 0,
        updated_at = p_now
      where observability_alert_state.alert_key = v_rule.alert_key;

      if not v_state.active
        and (
          v_state.last_triggered_at is null
          or v_state.last_triggered_at <=
            p_now - pg_catalog.make_interval(secs => v_rule.cooldown_seconds)
        )
      then
        update public.observability_alert_state
        set
          active = true,
          last_triggered_at = p_now,
          updated_at = p_now
        where observability_alert_state.alert_key = v_rule.alert_key;

        insert into public.observability_alert_events (
          alert_key,
          outcome,
          severity,
          metric_value,
          sample_count,
          threshold,
          window_seconds,
          destination,
          occurred_at
        )
        values (
          v_rule.alert_key,
          'triggered',
          v_rule.severity,
          v_metric_value,
          v_sample_count,
          v_rule.threshold,
          v_rule.window_seconds,
          v_rule.destination,
          p_now
        )
        returning id into v_event_id;

        perform pg_catalog.pg_notify(
          'alpha_dog_observability_alerts',
          pg_catalog.json_build_object(
            'alertKey',
            v_rule.alert_key,
            'eventId',
            v_event_id,
            'outcome',
            'triggered',
            'severity',
            v_rule.severity
          )::text
        );

        event_id := v_event_id;
        alert_key := v_rule.alert_key;
        outcome := 'triggered';
        severity := v_rule.severity;
        return next;
      end if;
    elsif v_state.active then
      update public.observability_alert_state
      set
        consecutive_healthy_samples = consecutive_healthy_samples + 1,
        updated_at = p_now
      where observability_alert_state.alert_key = v_rule.alert_key
      returning * into v_state;

      if v_state.consecutive_healthy_samples >=
        v_rule.recovery_consecutive_samples
      then
        update public.observability_alert_state
        set
          active = false,
          consecutive_healthy_samples = 0,
          last_recovered_at = p_now,
          updated_at = p_now
        where observability_alert_state.alert_key = v_rule.alert_key;

        insert into public.observability_alert_events (
          alert_key,
          outcome,
          severity,
          metric_value,
          sample_count,
          threshold,
          window_seconds,
          destination,
          occurred_at
        )
        values (
          v_rule.alert_key,
          'recovered',
          'info',
          v_metric_value,
          v_sample_count,
          v_rule.threshold,
          v_rule.window_seconds,
          v_rule.destination,
          p_now
        )
        returning id into v_event_id;

        perform pg_catalog.pg_notify(
          'alpha_dog_observability_alerts',
          pg_catalog.json_build_object(
            'alertKey',
            v_rule.alert_key,
            'eventId',
            v_event_id,
            'outcome',
            'recovered',
            'severity',
            'info'
          )::text
        );

        event_id := v_event_id;
        alert_key := v_rule.alert_key;
        outcome := 'recovered';
        severity := 'info';
        return next;
      end if;
    else
      update public.observability_alert_state
      set
        consecutive_healthy_samples = 0,
        updated_at = p_now
      where observability_alert_state.alert_key = v_rule.alert_key;
    end if;
  end loop;

  delete from public.observability_alert_samples
  where occurred_at < p_now - interval '24 hours';
end;
$$;

create or replace function public.record_observability_alert_sample(
  p_alert_key text,
  p_value numeric,
  p_occurred_at timestamptz default now()
)
returns table (
  event_id uuid,
  alert_key text,
  outcome text,
  severity text
)
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if p_occurred_at is null or p_value < 0 or p_value > 1000000000 then
    raise exception 'invalid alert sample';
  end if;

  insert into public.observability_alert_samples (
    alert_key,
    value,
    occurred_at
  )
  values (p_alert_key, p_value, p_occurred_at);

  return query
  select *
  from public.evaluate_observability_alerts(p_occurred_at);
end;
$$;

revoke all on function public.evaluate_observability_alerts(timestamptz)
  from public, anon, authenticated;
revoke all on function public.record_observability_alert_sample(
  text,
  numeric,
  timestamptz
) from public, anon, authenticated;
grant execute on function public.evaluate_observability_alerts(timestamptz)
  to service_role;
grant execute on function public.record_observability_alert_sample(
  text,
  numeric,
  timestamptz
) to service_role;

do $$
declare
  v_job_id bigint;
begin
  select jobid
  into v_job_id
  from cron.job
  where jobname = 'alpha-dog-observability-alert-evaluator';

  if v_job_id is not null then
    perform cron.unschedule(v_job_id);
  end if;

  perform cron.schedule(
    'alpha-dog-observability-alert-evaluator',
    '* * * * *',
    'select public.evaluate_observability_alerts();'
  );
end;
$$;
